### ISSUE TITLE
`Expect` macros don't work with string interpolation in Scala 2.13.14

### ISSUE THREAD

**Issue by aragutskiy** [disneystreaming/weaver-test#750]
After updating Scala from `2.13.13` to `2.13.14` I got compilation error: "possible missing interpolator: detected an interpolated expression".

Doesn't work:

```scala
val world = "World"
assert(s"Hello, $world!".contains("Hell"))
```

Works:

```scala
val world = "World"
val assertion = s"Hello, $world!".contains("Hell")
assert(assertion)
```

**Comment by SethTisue** [comment]
Curious what happened here — what Scala change was responsible.

**Comment by som-snytt** [comment]
Probably the same as https://github.com/etorreborre/specs2/issues/1237 
or explanation on the forum
https://users.scala-lang.org/t/regression-with-macro-and-interpolation-linting/9986/2?u=som-snytt

where `-Wmacros:after` (or `-Wmacros:both`) enables linting (for this particular lint) the tree after expansion.

Note that the new default `-Wmacros:default` was improved to make it less likely that `-Wmacros:after` is intended. 

(`-Wmacros:none` turns off linting of trees that are transformed by macros, either before or after expansion.)

**Comment by som-snytt** [comment]
I submitted a provisional PR with expecty, which I assume is used here. That would pass the lint irrespective of other settings.

**Comment by SethTisue** [comment]
> It ought to be mentioned in the release notes

ah, indeed, https://github.com/scala/scala/releases/tag/v2.13.14 references https://github.com/scala/scala/pull/10693

and the expecty PR Som mentions is https://github.com/eed3si9n/expecty/pull/161
